img_size: 512
img_dir:
ann_json:

transforms:
  _target_: albumentations.Compose
  transforms:
    - _target_: albumentations.SmallestMaxSize
      max_size: '${data.img_size}'

    - _target_: albumentations.RandomCrop
      height: '${data.img_size}'
      width: '${data.img_size}'

    - _target_: albumentations.HorizontalFlip

    - _target_: albumentations.ColorJitter
      brightness: 0.4
      contrast: 0.4
      saturation: 0.4
      hue: 0

    - _target_: albumentations.Normalize
      mean: [0,0,0]
      std: [1,1,1]

    - _target_: albumentations.pytorch.ToTensorV2

  bbox_params:
    _target_: albumentations.BboxParams
    format: coco
    label_fields: [labels]
    min_area: 1
