model:
  task: tracking
  backbone:
    name: resnet34
    pretrained: True
  
  neck:
    name: fpn
    upsample_channels: [256, 128, 64]
    upsample_type: nearest
    conv_type: normal
    use_fusion_weights: True

  output_heads:
    heatmap:
      num_classes: 1
      init_bias: -2.19
      target_method: cornernet
      loss_function: cornernet_focal
      loss_weight: 1

    box_2d:
      init_bias: 0
      loss_function: l1
      loss_weight: 0.1

    reid:
      init_bias: 0
      loss_function: ce
      max_track_ids: 800

  optimizer:
    name: SGD
    params:
      lr: 0.02
      momentum: 0.9
      weight_decay: 0.0001

  lr_scheduler:
    name: OneCycleLR
    params:
      max_lr: 0.02

data:
  train:
    dataset:
      type: mot-tracking
      data_dir: datasets/MOT/MOT17/train
      sequence_names:
      - MOT17-04-FRCNN    # 1050 frames
      - MOT17-11-FRCNN    # 900
      - MOT17-05-FRCNN    # 837
      - MOT17-13-FRCNN    # 750
      - MOT17-10-FRCNN    # 654

      transforms:
        HorizontalFlip:
          p: 0.5
        RandomResizedCrop:
          height: 1088
          width: 608
        ColorJitter:
          brightness: 0.4
          contrast: 0.4
          saturation: 0.4
  
    dataloader:
      batch_size: 16
      num_workers: 8
      shuffle: True
      pin_memory: True

  validation:
    dataset:
      type: mot-tracking
      data_dir: datasets/MOT/MOT17/train
      sequence_names:
      - MOT17-02-FRCNN    # 600
      - MOT17-09-FRCNN    # 525
      
      transforms:
        Resize:
          height: 608
          width: 1088
    
    dataloader:
      batch_size: 16
      num_workers: 8
      shuffle: False
      pin_memory: True

trainer:
  gpus: 1
  precision: 16
  max_epochs: 140
  val_check_interval: 1.0
  benchmark: True
  gradient_clip_val: 35

logger:
  name: wandb         # tensorboard or wandb
  params:
    project: mot17
    log_model: True
