model:
  backbone:
    name: resnet34
    pretrained: True
    upsample_channels: 256, 128, 64
    conv_upsample_block:
      upsample_type: conv_transpose     # conv_transpose, bilinear, neareast
      conv_type: normal                 # normal, separable, dcn
      deconv_params:                    # only used with conv_transpose
        kernel_size: 4                  
        stride: 2
        padding: 1
        output_padding: 0
        bias: False
      init_bilinear: True               # only used with conv_transpose
  
    skip_connection:                    # only used for fpn variants
      kernel_size: 1

  num_classes: 78
  output_heads:
    other_heads: [size, offset]
    heatmap_bias: -2.19
    loss_weights:
      size: 1
      offset: 1

data:
  train:
    data_dir: datasets/COCO
    coco: True
    coco_name: train2017
    batch_size: 16

  validation:
    data_dir: datasets/COCO
    coco: True
    coco_name: val2017
    batch_size: 16

trainer:
  gpus: 1
  precision: 16
  max_epochs: 10
  val_check_interval: 0.5

optimizer:
  name: adam
  params:
    lr: 0.0001

  lr_scheduler_name: None
  lr_scheduler_params: None
