__base__: base_resnet34.yaml

model:
  num_classes: 80

data:
  train:
    type: coco
    dataset_params:
      data_dir: datasets/COCO
      split: train2017
  
    transforms:
      - name: HorizontalFlip
        params:
          p: 0.5
      - name: Resize
        params:
          height: 512
          width: 512
      - name: ColorJitter
        params:
          brightness: 0.4
          contrast: 0.4
          saturation: 0.4

  validation:
    type: coco
    dataset_params:
      data_dir: datasets/COCO
      split: val2017

trainer:
  params:
    max_epochs: 10
  
  logger:
    name: wandb
    params:
      project: coco-centernet
      log_model: True
  
