MODEL:
  BACKBONE: 
    ARCHITECTURE: resnet50
    UPSAMPLE_INIT_BILINEAR: True
  
  OUTPUT_HEADS:
    OTHER_HEADS: [size, offset]
    HEATMAP_BIAS: -2.7
    LOSS_WEIGHTS:
      SIZE: 1
      OFFSET: 1

DATASET:
  TRAIN:
    DATA_DIR: datasets/COCO
    COCO: True
    COCO_NAME: train2017
  
  VALIDATION:
    DATA_DIR: datasets/COCO
    COCO: True
    COCO_NAME: val2017

TRAINER:
  EPOCHS: 1
  BATCH_SIZE: 16
  LEARNING_RATE: 0.0001
  OPTIMIZER: adam
