model:
  backbone:
    name: resnet34
    upsample_channels: 256, 128, 64
    upsample_block:
      conv_first: True
      upsample_type: conv_transpose     # conv_transpose, bilinear, neareast
      conv_type: normal                 # normal, separable, dcn
      deconv_kernel: 4                  # only used with conv_transpose
      init_bilinear: True               # only used with conv_transpose
  
  num_classes: 78
  output_heads:
    other_heads: [size, offset]
    heatmap_bias: -4.595
    loss_weights:
      size: 1
      offset: 1

data:
  train:
    data_dir: datasets/COCO
    coco: True
    coco_name: train2017
    batch_size: 16

  validation:
    data_dir: datasets/COCO
    coco: True
    coco_name: val2017
    batch_size: 16

trainer:
  gpus: 1
  precision: 16
  max_epochs: 10
  val_check_interval: 0.5
  callbacks:

  optimizer:
    name: adam
    lr: 0.0001
  