__base__: "base_resnet34.yaml"

model:
  backbone:
    name: resnet34
    pretrained: True

  output_heads:
    heatmap:
      num_classes: 2

data:
  train:
    dataset:
      type: voc
      data_dir: datasets/VOC2028/
      split: train
      name_to_label: &helmet_name_to_label
        person: 0
        hat: 1

  validation:
    dataset:
      type: voc
      data_dir: datasets/VOC2028/
      split: val
      name_to_label: *helmet_name_to_label

# trainer:
#   params:
#     max_epochs: 20
  
logger:
  name: wandb
  params:
    project: helmet
    log_model: True
