model:
  backbone:
    name: resnet34
    upsample_channels: [256, 128, 64]
    conv_upsample_block:
      upsample_type: conv_transpose     # conv_transpose, bilinear, neareast
      conv_type: normal                 # normal, separable, dcn
      deconv_kernel: 4                  # only used with conv_transpose
      init_bilinear: True               # only used with conv_transpose
  
  num_classes: 2
  heatmap_method: ttfnet       # cornernet or ttfnet

  output_heads:
    other_heads: [size, offset]
    fill_bias: 
      heatmap: -2.19
      size: 0
      offset: 0
    loss_weights:
      heatmap: 1
      size: 0.1
      offset: 1
    loss_functions:
      size: L1Loss      # a loss from torch.nn e.g. L1Loss, SmoothL1Loss
      offset: L1Loss

  optimizer:           # mmdetection
    name: Adam          # any optimizers from torch.optim
    params:
      lr: 0.001
      weight_decay: 0.0001

  # lr_scheduler:
  #   name: OneCycleLR    # any lr_scheduler from torch.optim.lr_scheduler
  #   params:
  #     max_lr: 0.02

data:
  train:
    type: voc
    dataset_params:
      data_dir: datasets/VOC2028/
      split: train
      name_to_label: &helmet_name_to_label
        person: 0
        hat: 1
    
    dataloader_params:
      batch_size: 32
      num_workers: 8
      shuffle: True
      pin_memory: True
    
    transforms:
      # augmentations used in CenterNet paper
      # https://github.com/xingyizhou/CenterNet/blob/master/src/lib/utils/image.py#L222
      # they also used PCA augmentation, but didn't mention in their paper
      - name: HorizontalFlip        # any transformations from Albumentation
        params:
          p: 0.5
      - name: RandomResizedCrop
        params:
          height: 512
          width: 512
      - name: ColorJitter
        params:
          brightness: 0.4
          contrast: 0.4
          saturation: 0.4

  validation:
    type: voc
    dataset_params:
      data_dir: datasets/VOC2028/
      split: val
      name_to_label: *helmet_name_to_label
    
    dataloader_params:
      batch_size: 32
      num_workers: 8
      shuffle: False
      pin_memory: True
    
    transforms:
      - name: Resize
        params:
          height: 512
          width: 512

trainer:
  params:
    gpus: 1
    precision: 16
    max_epochs: 50
    val_check_interval: 1.0
    benchmark: True
    gradient_clip_val: 35     # mmdetection

  logger:
    name: wandb         # tensorboard or wandb
    params:
      project: helmet
      log_model: True
